name: Deploy EC2 using Terraform

on:
  workflow_dispatch:
    inputs:
      configuration_folder:
        description: 'Select the Terraform folder to apply (e.g., ec2, vpc, s3, lambda). This workflow uses the terraform-module from: https://github.com/vikrantyadav1996/terraform-module.git'
        required: true
        type: choice
        options:
          - ec2
          - vpc
          - s3
          - lambda
        default: 'ec2'
      ec2_instance_type:
        description: 'EC2 Instance Type'
        required: true
        default: 't3.micro'
      ami_id:
        description: 'AMI ID'
        required: true
        default: 'ami-08eb150f611ca277f'  # Default AMI ID

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the current repo (Repo-B)
      - name: Checkout Repo-B
        uses: actions/checkout@v3

      # Checkout Repo-A (Terraform Module)
      - name: Checkout Repo-A (Terraform Module)
        uses: actions/checkout@v3
        with:
          repository: vikrantyadav1996/terraform-module
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token stored in secrets
          path: terraform-module

      # Debug: List files in terraform-module folder to confirm folder structure
      - name: List files in terraform-module
        run: |
          ls -R terraform-module  # List the contents of the terraform-module folder

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.3.5'

      # Initialize Terraform
      - name: Terraform Init
        run: |
          echo "Current directory before cd:"
          pwd
          echo "Listing files before cd:"
          ls -al
          
          # Navigate to the selected folder in Repo-A
          cd terraform-module/${{ github.event.inputs.configuration_folder }}
          
          # Run Terraform Init
          terraform init

      # Configure AWS credentials using secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS Access Key from Secrets
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS Secret Key from Secrets
          aws_region: eu-north-1

      # Terraform Plan (Optional but recommended)
      - name: Terraform Plan
        run: |
          cd terraform-module/${{ github.event.inputs.configuration_folder }}
          terraform plan -var "ec2_instance_type=${{ github.event.inputs.ec2_instance_type }}" -var "ami_id=${{ github.event.inputs.ami_id }}"

      # Apply Terraform using input variables
      - name: Terraform Apply
        run: |
          cd terraform-module/${{ github.event.inputs.configuration_folder }}
          terraform apply -var "ec2_instance_type=${{ github.event.inputs.ec2_instance_type }}" -var "ami_id=${{ github.event.inputs.ami_id }}" -auto-approve
