name: Terraform Workflow

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger this workflow on pull requests targeting main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code of your app repository
      - name: Checkout my-app-repo
        uses: actions/checkout@v2

      # Step 2: Checkout the terraform-module repository where your modules are stored
      - name: Checkout terraform-module repository
        uses: actions/checkout@v2
        with:
          repository: vikrantyadav1996/terraform-module  # Your terraform-module repo
          path: terraform-module  # This will check out your repo under the 'terraform-module' folder

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.7  # You can specify the version you want to use

      # Step 4: Initialize Terraform (in the ec2 module directory)
      - name: Terraform Init
        working-directory: terraform-module/module/ec2  # Set the working directory to the ec2 module
        run: terraform init

      # Step 5: Run Terraform Plan (optional)
      - name: Terraform Plan
        working-directory: terraform-module/module/ec2
        run: terraform plan

      # Step 6: Apply the Terraform code (optional)
      - name: Terraform Apply
        working-directory: terraform-module/module/ec2
        run: terraform apply -auto-approve  # Run with auto-approve flag (be cautious)
